name: Econsult
favicon: null
layout_spectrum: 0.28389547555707395
typography_spectrum: 0.5798441735096276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.38555069267749786
  lightness: 0.20395884988829494
  saturation: 0.8671124803368002
  rhythmicContrast: 0.7799331096466631
purpose: []
