name: Econsult
favicon: null
layout_spectrum: 0.00286
typography_spectrum: 0.4315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0c0e'
    - '#4e4e4e'
    - '#cda58c'
    - '#f7dccb'
    - '#58131b'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
