name: Econsult
favicon: null
layout_spectrum: 0.28389547555707395
typography_spectrum: 0.5798441735096276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfc4af'
    - '#040500'
    - '#695652'
    - '#2c7fa9'
    - '#831400'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.7799331096466631
purpose: []
